use super::BlockEntityData;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockEntityVariant {
    Banners,
    Barrels,
    Beacons,
    Beds,
    Beehives,
    Bell,
    BlastFurnace,
    BrewingStand,
    CalibratedSculkSensor,
    Campfire,
    ChiseledBookshelf,
    Chest,
    Comparator,
    CommandBlock,
    Conduit,
    Crafter,
    DaylightDetector,
    DecoratedPot,
    Dispenser,
    Dropper,
    EnchantingTable,
    EnderChest,
    EndGateway,
    EndPortal,
    Furnace,
    HangingSign,
    Hopper,
    Jigsaw,
    Jukebox,
    Lectern,
    MobSpawner,
    Piston,
    SculkCatalyst,
    SculkSensor,
    SculkShrieker,
    ShulkerBox,
    Sign,
    Skull,
    StructureBlock,
    Smoker,
    SoulCampfire,
    SuspiciousGravel,
    SuspiciousSand,
    TrappedChest,
    TrialSpawner,
    Vault,
}

impl<'a> BlockEntityData<'a> {
    pub fn variant(&self) -> BlockEntityVariant {
        match self {
            BlockEntityData::Banners(_) => BlockEntityVariant::Banners,
            BlockEntityData::Barrel(_) => BlockEntityVariant::Barrels,
            BlockEntityData::Beacon(_) => BlockEntityVariant::Beacons,
            BlockEntityData::Bed => BlockEntityVariant::Beds,
            BlockEntityData::Beehive(_) => BlockEntityVariant::Beehives,
            BlockEntityData::Bell => BlockEntityVariant::Bell,
            BlockEntityData::BlastFurnace(_) => BlockEntityVariant::BlastFurnace,
            BlockEntityData::BrewingStand(_) => BlockEntityVariant::BrewingStand,
            BlockEntityData::CalibratedSculkSensor(_) => BlockEntityVariant::CalibratedSculkSensor,
            BlockEntityData::Campfire(_) => BlockEntityVariant::Campfire,
            BlockEntityData::ChiseledBookshelf(_) => BlockEntityVariant::ChiseledBookshelf,
            BlockEntityData::Chest(_) => BlockEntityVariant::Chest,
            BlockEntityData::Comparator(_) => BlockEntityVariant::Comparator,
            BlockEntityData::CommandBlock(_) => BlockEntityVariant::CommandBlock,
            BlockEntityData::Conduit(_) => BlockEntityVariant::Conduit,
            BlockEntityData::Crafter(_) => BlockEntityVariant::Crafter,
            BlockEntityData::DaylightDetector => BlockEntityVariant::DaylightDetector,
            BlockEntityData::DecoratedPot(_) => BlockEntityVariant::DecoratedPot,
            BlockEntityData::Dispenser(_) => BlockEntityVariant::Dispenser,
            BlockEntityData::Dropper(_) => BlockEntityVariant::Dropper,
            BlockEntityData::EnchantingTable(_) => BlockEntityVariant::EnchantingTable,
            BlockEntityData::EnderChest => BlockEntityVariant::EnderChest,
            BlockEntityData::EndGateway(_) => BlockEntityVariant::EndGateway,
            BlockEntityData::EndPortal => BlockEntityVariant::EndPortal,
            BlockEntityData::Furnace(_) => BlockEntityVariant::Furnace,
            BlockEntityData::HangingSing(_) => BlockEntityVariant::HangingSign,
            BlockEntityData::Hopper(_) => BlockEntityVariant::Hopper,
            BlockEntityData::Jigsaw(_) => BlockEntityVariant::Jigsaw,
            BlockEntityData::Jukebox(_) => BlockEntityVariant::Jukebox,
            BlockEntityData::Lectern(_) => BlockEntityVariant::Lectern,
            BlockEntityData::MobSpawner(_) => BlockEntityVariant::MobSpawner,
            BlockEntityData::Piston(_) => BlockEntityVariant::Piston,
            BlockEntityData::SculkCatalyst(_) => BlockEntityVariant::SculkCatalyst,
            BlockEntityData::SculkSensor(_) => BlockEntityVariant::SculkSensor,
            BlockEntityData::SculkShrieker(_) => BlockEntityVariant::SculkShrieker,
            BlockEntityData::ShulkerBox(_) => BlockEntityVariant::ShulkerBox,
            BlockEntityData::Sign(_) => BlockEntityVariant::Sign,
            BlockEntityData::Skull(_) => BlockEntityVariant::Skull,
            BlockEntityData::StructureBlock(_) => BlockEntityVariant::StructureBlock,
            BlockEntityData::Smoker(_) => BlockEntityVariant::Smoker,
            BlockEntityData::SoulCampfire(_) => BlockEntityVariant::SoulCampfire,
            BlockEntityData::SuspiciousGravel(_) => BlockEntityVariant::SuspiciousGravel,
            BlockEntityData::SuspiciousSand(_) => BlockEntityVariant::SuspiciousSand,
            BlockEntityData::TrappedChest(_) => BlockEntityVariant::TrappedChest,
            BlockEntityData::TrialSpawner(_) => BlockEntityVariant::TrialSpawner,
            BlockEntityData::Vault(_) => BlockEntityVariant::Vault,
        }
    }
}
