pub use crate::block_entities::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum BlockEntityVariant {
    Banners,
    Barrels,
    Beacons,
    Beds,
    Beehives,
    Bell,
    BlastFurnace,
    BrewingStand,
    CalibratedSculkSensor,
    Campfire,
    ChiseledBookshelf,
    Chest,
    Comparator,
    CommandBlock,
    Conduit,
    Crafter,
    DaylightDetector,
    DecoratedPot,
    Dispenser,
    Dropper,
    EnchantingTable,
    EnderChest,
    EndGateway,
    EndPortal,
    Furnace,
    HangingSign,
    Hopper,
    Jigsaw,
    Jukebox,
    Lectern,
    MobSpawner,
    Piston,
    SculkCatalyst,
    SculkSensor,
    SculkShrieker,
    ShulkerBox,
    Sign,
    Skull,
    StructureBlock,
    Smoker,
    SoulCampfire,
    SuspiciousGravel,
    SuspiciousSand,
    TrappedChest,
    TrialSpawner,
    Vault,
}

impl BlockEntityKind {
    pub fn variant(&self) -> BlockEntityVariant {
        match self {
            BlockEntityKind::Banners(_) => BlockEntityVariant::Banners,
            BlockEntityKind::Barrel(_) => BlockEntityVariant::Barrels,
            BlockEntityKind::Beacon(_) => BlockEntityVariant::Beacons,
            BlockEntityKind::Bed => BlockEntityVariant::Beds,
            BlockEntityKind::Beehive(_) => BlockEntityVariant::Beehives,
            BlockEntityKind::Bell => BlockEntityVariant::Bell,
            BlockEntityKind::BlastFurnace(_) => BlockEntityVariant::BlastFurnace,
            BlockEntityKind::BrewingStand(_) => BlockEntityVariant::BrewingStand,
            BlockEntityKind::CalibratedSculkSensor(_) => BlockEntityVariant::CalibratedSculkSensor,
            BlockEntityKind::Campfire(_) => BlockEntityVariant::Campfire,
            BlockEntityKind::ChiseledBookshelf(_) => BlockEntityVariant::ChiseledBookshelf,
            BlockEntityKind::Chest(_) => BlockEntityVariant::Chest,
            BlockEntityKind::Comparator(_) => BlockEntityVariant::Comparator,
            BlockEntityKind::CommandBlock(_) => BlockEntityVariant::CommandBlock,
            BlockEntityKind::Conduit(_) => BlockEntityVariant::Conduit,
            BlockEntityKind::Crafter(_) => BlockEntityVariant::Crafter,
            BlockEntityKind::DaylightDetector => BlockEntityVariant::DaylightDetector,
            BlockEntityKind::DecoratedPot(_) => BlockEntityVariant::DecoratedPot,
            BlockEntityKind::Dispenser(_) => BlockEntityVariant::Dispenser,
            BlockEntityKind::Dropper(_) => BlockEntityVariant::Dropper,
            BlockEntityKind::EnchantingTable(_) => BlockEntityVariant::EnchantingTable,
            BlockEntityKind::EnderChest => BlockEntityVariant::EnderChest,
            BlockEntityKind::EndGateway(_) => BlockEntityVariant::EndGateway,
            BlockEntityKind::EndPortal => BlockEntityVariant::EndPortal,
            BlockEntityKind::Furnace(_) => BlockEntityVariant::Furnace,
            BlockEntityKind::HangingSign(_) => BlockEntityVariant::HangingSign,
            BlockEntityKind::Hopper(_) => BlockEntityVariant::Hopper,
            BlockEntityKind::Jigsaw(_) => BlockEntityVariant::Jigsaw,
            BlockEntityKind::Jukebox(_) => BlockEntityVariant::Jukebox,
            BlockEntityKind::Lectern(_) => BlockEntityVariant::Lectern,
            BlockEntityKind::MobSpawner(_) => BlockEntityVariant::MobSpawner,
            BlockEntityKind::Piston(_) => BlockEntityVariant::Piston,
            BlockEntityKind::SculkCatalyst(_) => BlockEntityVariant::SculkCatalyst,
            BlockEntityKind::SculkSensor(_) => BlockEntityVariant::SculkSensor,
            BlockEntityKind::SculkShrieker(_) => BlockEntityVariant::SculkShrieker,
            BlockEntityKind::ShulkerBox(_) => BlockEntityVariant::ShulkerBox,
            BlockEntityKind::Sign(_) => BlockEntityVariant::Sign,
            BlockEntityKind::Skull(_) => BlockEntityVariant::Skull,
            BlockEntityKind::StructureBlock(_) => BlockEntityVariant::StructureBlock,
            BlockEntityKind::Smoker(_) => BlockEntityVariant::Smoker,
            BlockEntityKind::SoulCampfire(_) => BlockEntityVariant::SoulCampfire,
            BlockEntityKind::SuspiciousGravel(_) => BlockEntityVariant::SuspiciousGravel,
            BlockEntityKind::SuspiciousSand(_) => BlockEntityVariant::SuspiciousSand,
            BlockEntityKind::TrappedChest(_) => BlockEntityVariant::TrappedChest,
            BlockEntityKind::TrialSpawner(_) => BlockEntityVariant::TrialSpawner,
            BlockEntityKind::Vault(_) => BlockEntityVariant::Vault,
        }
    }
}
