use super::BlockEntityData;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockEntityVariant {
    Barrels,
    Beacons,
    Beds,
    Beehives,
    Bell,
    BlastFurnace,
    BrewingStand,
    CalibratedSculkSensor,
    Campfire,
    ChiseledBookshelf,
    Chest,
    Comparator,
    CommandBlock,
    Conduit,
    Crafter,
    DaylightDetector,
    DecoratedPot,
    Dispenser,
    Dropper,
    EnchantingTable,
    EnderChest,
    EndGateway,
    EndPortal,
    Furnace,
    Hopper,
    Jigsaw,
    Jukebox,
    Lectern,
    MobSpawner,
    Piston,
    SculkCatalyst,
    SculkSensor,
    SculkShrieker,
    StructureBlock,
    Smoker,
    SoulCampfire,
    SuspiciousGravel,
    SuspiciousSand,
    TrappedChest,
    TrialSpawner,
    Vault,
    SkeletonSkull,
    SkeletonWallSkull,
    WitherSkeletonSkull,
    WitherSkeletonWallSkull,
    ZombieHead,
    ZombieWallHead,
    PlayerHead,
    PlayerWallHead,
    CreeperHead,
    CreeperWallHead,
    DragonHead,
    DragonWallHead,
    PiglinHead,
    PiglinWallHead,
    OakHangingSign,
    OakWallHangingSign,
    SpruceHangingSign,
    SpruceWallHangingSign,
    BirchHangingSign,
    BirchWallHangingSign,
    JungleHangingSign,
    JungleWallHangingSign,
    AcaciaHangingSign,
    AcaciaWallHangingSign,
    DarkOakHangingSign,
    DarkOakWallHangingSign,
    MangroveHangingSign,
    MangroveWallHangingSign,
    CherryHangingSign,
    CherryWallHangingSign,
    BambooHangingSign,
    BambooWallHangingSign,
    CrimsonHangingSign,
    CrimsonWallHangingSign,
    WarpedHangingSign,
    WarpedWallHangingSign,
    OakSign,
    OakWallSign,
    SpruceSign,
    SpruceWallSign,
    BirchSign,
    BirchWallSign,
    JungleSign,
    JungleWallSign,
    AcaciaSign,
    AcaciaWallSign,
    DarkOakSign,
    DarkOakWallSign,
    MangroveSign,
    MangroveWallSign,
    CherrySign,
    CherryWallSign,
    BambooSign,
    BambooWallSign,
    CrimsonSign,
    CrimsonWallSign,
    WarpedSign,
    WarpedWallSign,
    WhiteShulkerBox,
    OrangeShulkerBox,
    MagentaShulkerBox,
    LightBlueShulkerBox,
    YellowShulkerBox,
    LimeShulkerBox,
    PinkShulkerBox,
    GrayShulkerBox,
    LightGrayShulkerBox,
    CyanShulkerBox,
    PurpleShulkerBox,
    BlueShulkerBox,
    BrownShulkerBox,
    GreenShulkerBox,
    RedShulkerBox,
    BlackShulkerBox,
    WhiteBed,
    OrangeBed,
    MagentaBed,
    LightBlueBed,
    YellowBed,
    LimeBed,
    PinkBed,
    GrayBed,
    LightGrayBed,
    CyanBed,
    PurpleBed,
    BlueBed,
    BrownBed,
    GreenBed,
    RedBed,
    BlackBed,
    WhiteBanner,
    OrangeBanner,
    MagentaBanner,
    LightBlueBanner,
    YellowBanner,
    LimeBanner,
    PinkBanner,
    GrayBanner,
    LightGrayBanner,
    CyanBanner,
    PurpleBanner,
    BlueBanner,
    BrownBanner,
    GreenBanner,
    RedBanner,
    BlackBanner,
    WhiteWallBanner,
    OrangeWallBanner,
    MagentaWallBanner,
    LightBlueWallBanner,
    YellowWallBanner,
    LimeWallBanner,
    PinkWallBanner,
    GrayWallBanner,
    LightGrayWallBanner,
    CyanWallBanner,
    PurpleWallBanner,
    BlueWallBanner,
    BrownWallBanner,
    GreenWallBanner,
    RedWallBanner,
    BlackWallBanner,
}

impl<'a> BlockEntityData<'a> {
    pub fn variant(&self) -> BlockEntityVariant {
        match self {
            BlockEntityData::Barrel(_) => BlockEntityVariant::Barrels,
            BlockEntityData::Beacon(_) => BlockEntityVariant::Beacons,
            BlockEntityData::Beehive(_) => BlockEntityVariant::Beehives,
            BlockEntityData::Bell => BlockEntityVariant::Bell,
            BlockEntityData::BlastFurnace(_) => BlockEntityVariant::BlastFurnace,
            BlockEntityData::BrewingStand(_) => BlockEntityVariant::BrewingStand,
            BlockEntityData::CalibratedSculkSensor(_) => BlockEntityVariant::CalibratedSculkSensor,
            BlockEntityData::Campfire(_) => BlockEntityVariant::Campfire,
            BlockEntityData::ChiseledBookshelf(_) => BlockEntityVariant::ChiseledBookshelf,
            BlockEntityData::Chest(_) => BlockEntityVariant::Chest,
            BlockEntityData::Comparator(_) => BlockEntityVariant::Comparator,
            BlockEntityData::CommandBlock(_) => BlockEntityVariant::CommandBlock,
            BlockEntityData::Conduit(_) => BlockEntityVariant::Conduit,
            BlockEntityData::Crafter(_) => BlockEntityVariant::Crafter,
            BlockEntityData::DaylightDetector => BlockEntityVariant::DaylightDetector,
            BlockEntityData::DecoratedPot(_) => BlockEntityVariant::DecoratedPot,
            BlockEntityData::Dispenser(_) => BlockEntityVariant::Dispenser,
            BlockEntityData::Dropper(_) => BlockEntityVariant::Dropper,
            BlockEntityData::EnchantingTable(_) => BlockEntityVariant::EnchantingTable,
            BlockEntityData::EnderChest => BlockEntityVariant::EnderChest,
            BlockEntityData::EndGateway(_) => BlockEntityVariant::EndGateway,
            BlockEntityData::EndPortal => BlockEntityVariant::EndPortal,
            BlockEntityData::Furnace(_) => BlockEntityVariant::Furnace,
            BlockEntityData::Hopper(_) => BlockEntityVariant::Hopper,
            BlockEntityData::Jigsaw(_) => BlockEntityVariant::Jigsaw,
            BlockEntityData::Jukebox(_) => BlockEntityVariant::Jukebox,
            BlockEntityData::Lectern(_) => BlockEntityVariant::Lectern,
            BlockEntityData::MobSpawner(_) => BlockEntityVariant::MobSpawner,
            BlockEntityData::Piston(_) => BlockEntityVariant::Piston,
            BlockEntityData::SculkCatalyst(_) => BlockEntityVariant::SculkCatalyst,
            BlockEntityData::SculkSensor(_) => BlockEntityVariant::SculkSensor,
            BlockEntityData::SculkShrieker(_) => BlockEntityVariant::SculkShrieker,
            BlockEntityData::StructureBlock(_) => BlockEntityVariant::StructureBlock,
            BlockEntityData::Smoker(_) => BlockEntityVariant::Smoker,
            BlockEntityData::SoulCampfire(_) => BlockEntityVariant::SoulCampfire,
            BlockEntityData::SuspiciousGravel(_) => BlockEntityVariant::SuspiciousGravel,
            BlockEntityData::SuspiciousSand(_) => BlockEntityVariant::SuspiciousSand,
            BlockEntityData::TrappedChest(_) => BlockEntityVariant::TrappedChest,
            BlockEntityData::TrialSpawner(_) => BlockEntityVariant::TrialSpawner,
            BlockEntityData::Vault(_) => BlockEntityVariant::Vault,
            //
            BlockEntityData::SkeletonSkull(_) => BlockEntityVariant::SkeletonSkull,
            BlockEntityData::SkeletonWallSkull(_) => BlockEntityVariant::SkeletonWallSkull,
            BlockEntityData::WitherSkeletonSkull(_) => BlockEntityVariant::WitherSkeletonSkull,
            BlockEntityData::WitherSkeletonWallSkull(_) => {
                BlockEntityVariant::WitherSkeletonWallSkull
            }
            BlockEntityData::ZombieHead(_) => BlockEntityVariant::ZombieHead,
            BlockEntityData::ZombieWallHead(_) => BlockEntityVariant::ZombieWallHead,
            BlockEntityData::PlayerHead(_) => BlockEntityVariant::PlayerHead,
            BlockEntityData::PlayerWallHead(_) => BlockEntityVariant::PlayerWallHead,
            BlockEntityData::CreeperHead(_) => BlockEntityVariant::CreeperHead,
            BlockEntityData::CreeperWallHead(_) => BlockEntityVariant::CreeperWallHead,
            BlockEntityData::DragonHead(_) => BlockEntityVariant::DragonHead,
            BlockEntityData::DragonWallHead(_) => BlockEntityVariant::DragonWallHead,
            BlockEntityData::PiglinHead(_) => BlockEntityVariant::PiglinHead,
            BlockEntityData::PiglinWallHead(_) => BlockEntityVariant::PiglinWallHead,
            //
            BlockEntityData::OakHangingSign(_) => BlockEntityVariant::OakHangingSign,
            BlockEntityData::OakWallHangingSign(_) => BlockEntityVariant::OakWallHangingSign,
            BlockEntityData::SpruceHangingSign(_) => BlockEntityVariant::SpruceHangingSign,
            BlockEntityData::SpruceWallHangingSign(_) => BlockEntityVariant::SpruceWallHangingSign,
            BlockEntityData::BirchHangingSign(_) => BlockEntityVariant::BirchHangingSign,
            BlockEntityData::BirchWallHangingSign(_) => BlockEntityVariant::BirchWallHangingSign,
            BlockEntityData::JungleHangingSign(_) => BlockEntityVariant::JungleHangingSign,
            BlockEntityData::JungleWallHangingSign(_) => BlockEntityVariant::JungleWallHangingSign,
            BlockEntityData::AcaciaHangingSign(_) => BlockEntityVariant::AcaciaHangingSign,
            BlockEntityData::AcaciaWallHangingSign(_) => BlockEntityVariant::AcaciaWallHangingSign,
            BlockEntityData::DarkOakHangingSign(_) => BlockEntityVariant::DarkOakHangingSign,
            BlockEntityData::DarkOakWallHangingSign(_) => {
                BlockEntityVariant::DarkOakWallHangingSign
            }
            BlockEntityData::MangroveHangingSign(_) => BlockEntityVariant::MangroveHangingSign,
            BlockEntityData::MangroveWallHangingSign(_) => {
                BlockEntityVariant::MangroveWallHangingSign
            }
            BlockEntityData::CherryHangingSign(_) => BlockEntityVariant::CherryHangingSign,
            BlockEntityData::CherryWallHangingSign(_) => BlockEntityVariant::CherryWallHangingSign,
            BlockEntityData::BambooHangingSign(_) => BlockEntityVariant::BambooHangingSign,
            BlockEntityData::BambooWallHangingSign(_) => BlockEntityVariant::BambooWallHangingSign,
            BlockEntityData::CrimsonHangingSign(_) => BlockEntityVariant::CrimsonHangingSign,
            BlockEntityData::CrimsonWallHangingSign(_) => {
                BlockEntityVariant::CrimsonWallHangingSign
            }
            BlockEntityData::WarpedHangingSign(_) => BlockEntityVariant::WarpedHangingSign,
            BlockEntityData::WarpedWallHangingSign(_) => BlockEntityVariant::WarpedWallHangingSign,
            //
            BlockEntityData::OakSign(_) => BlockEntityVariant::OakSign,
            BlockEntityData::OakWallSign(_) => BlockEntityVariant::OakWallSign,
            BlockEntityData::SpruceSign(_) => BlockEntityVariant::SpruceSign,
            BlockEntityData::SpruceWallSign(_) => BlockEntityVariant::SpruceWallSign,
            BlockEntityData::BirchSign(_) => BlockEntityVariant::BirchSign,
            BlockEntityData::BirchWallSign(_) => BlockEntityVariant::BirchWallSign,
            BlockEntityData::JungleSign(_) => BlockEntityVariant::JungleSign,
            BlockEntityData::JungleWallSign(_) => BlockEntityVariant::JungleWallSign,
            BlockEntityData::AcaciaSign(_) => BlockEntityVariant::AcaciaSign,
            BlockEntityData::AcaciaWallSign(_) => BlockEntityVariant::AcaciaWallSign,
            BlockEntityData::DarkOakSign(_) => BlockEntityVariant::DarkOakSign,
            BlockEntityData::DarkOakWallSign(_) => BlockEntityVariant::DarkOakWallSign,
            BlockEntityData::MangroveSign(_) => BlockEntityVariant::MangroveSign,
            BlockEntityData::MangroveWallSign(_) => BlockEntityVariant::MangroveWallSign,
            BlockEntityData::CherrySign(_) => BlockEntityVariant::CherrySign,
            BlockEntityData::CherryWallSign(_) => BlockEntityVariant::CherryWallSign,
            BlockEntityData::BambooSign(_) => BlockEntityVariant::BambooSign,
            BlockEntityData::BambooWallSign(_) => BlockEntityVariant::BambooWallSign,
            BlockEntityData::CrimsonSign(_) => BlockEntityVariant::CrimsonSign,
            BlockEntityData::CrimsonWallSign(_) => BlockEntityVariant::CrimsonWallSign,
            BlockEntityData::WarpedSign(_) => BlockEntityVariant::WarpedSign,
            BlockEntityData::WarpedWallSign(_) => BlockEntityVariant::WarpedWallSign,
            //
            BlockEntityData::WhiteShulkerBox(_) => BlockEntityVariant::WhiteShulkerBox,
            BlockEntityData::OrangeShulkerBox(_) => BlockEntityVariant::OrangeShulkerBox,
            BlockEntityData::MagentaShulkerBox(_) => BlockEntityVariant::MagentaShulkerBox,
            BlockEntityData::LightBlueShulkerBox(_) => BlockEntityVariant::LightBlueShulkerBox,
            BlockEntityData::YellowShulkerBox(_) => BlockEntityVariant::YellowShulkerBox,
            BlockEntityData::LimeShulkerBox(_) => BlockEntityVariant::LimeShulkerBox,
            BlockEntityData::PinkShulkerBox(_) => BlockEntityVariant::PinkShulkerBox,
            BlockEntityData::GrayShulkerBox(_) => BlockEntityVariant::GrayShulkerBox,
            BlockEntityData::LightGrayShulkerBox(_) => BlockEntityVariant::LightGrayShulkerBox,
            BlockEntityData::CyanShulkerBox(_) => BlockEntityVariant::CyanShulkerBox,
            BlockEntityData::PurpleShulkerBox(_) => BlockEntityVariant::PurpleShulkerBox,
            BlockEntityData::BlueShulkerBox(_) => BlockEntityVariant::BlueShulkerBox,
            BlockEntityData::BrownShulkerBox(_) => BlockEntityVariant::BrownShulkerBox,
            BlockEntityData::GreenShulkerBox(_) => BlockEntityVariant::GreenShulkerBox,
            BlockEntityData::RedShulkerBox(_) => BlockEntityVariant::RedShulkerBox,
            BlockEntityData::BlackShulkerBox(_) => BlockEntityVariant::BlackShulkerBox,
            //
            BlockEntityData::WhiteBed => BlockEntityVariant::WhiteBed,
            BlockEntityData::OrangeBed => BlockEntityVariant::OrangeBed,
            BlockEntityData::MagentaBed => BlockEntityVariant::MagentaBed,
            BlockEntityData::LightBlueBed => BlockEntityVariant::LightBlueBed,
            BlockEntityData::YellowBed => BlockEntityVariant::YellowBed,
            BlockEntityData::LimeBed => BlockEntityVariant::LimeBed,
            BlockEntityData::PinkBed => BlockEntityVariant::PinkBed,
            BlockEntityData::GrayBed => BlockEntityVariant::GrayBed,
            BlockEntityData::LightGrayBed => BlockEntityVariant::LightGrayBed,
            BlockEntityData::CyanBed => BlockEntityVariant::CyanBed,
            BlockEntityData::PurpleBed => BlockEntityVariant::PurpleBed,
            BlockEntityData::BlueBed => BlockEntityVariant::BlueBed,
            BlockEntityData::BrownBed => BlockEntityVariant::BrownBed,
            BlockEntityData::GreenBed => BlockEntityVariant::GreenBed,
            BlockEntityData::RedBed => BlockEntityVariant::RedBed,
            BlockEntityData::BlackBed => BlockEntityVariant::BlackBed,
            //
            BlockEntityData::WhiteBanner(_) => BlockEntityVariant::WhiteBanner,
            BlockEntityData::WhiteWallBanner(_) => BlockEntityVariant::WhiteWallBanner,
            BlockEntityData::OrangeBanner(_) => BlockEntityVariant::OrangeBanner,
            BlockEntityData::OrangeWallBanner(_) => BlockEntityVariant::OrangeWallBanner,
            BlockEntityData::MagentaBanner(_) => BlockEntityVariant::MagentaBanner,
            BlockEntityData::MagentaWallBanner(_) => BlockEntityVariant::MagentaWallBanner,
            BlockEntityData::LightBlueBanner(_) => BlockEntityVariant::LightBlueBanner,
            BlockEntityData::LightBlueWallBanner(_) => BlockEntityVariant::LightBlueWallBanner,
            BlockEntityData::YellowBanner(_) => BlockEntityVariant::YellowBanner,
            BlockEntityData::YellowWallBanner(_) => BlockEntityVariant::YellowWallBanner,
            BlockEntityData::LimeBanner(_) => BlockEntityVariant::LimeBanner,
            BlockEntityData::LimeWallBanner(_) => BlockEntityVariant::LimeWallBanner,
            BlockEntityData::PinkBanner(_) => BlockEntityVariant::PinkBanner,
            BlockEntityData::PinkWallBanner(_) => BlockEntityVariant::PinkWallBanner,
            BlockEntityData::GrayBanner(_) => BlockEntityVariant::GrayBanner,
            BlockEntityData::GrayWallBanner(_) => BlockEntityVariant::GrayWallBanner,
            BlockEntityData::LightGrayBanner(_) => BlockEntityVariant::LightGrayBanner,
            BlockEntityData::LightGrayWallBanner(_) => BlockEntityVariant::LightGrayWallBanner,
            BlockEntityData::CyanBanner(_) => BlockEntityVariant::CyanBanner,
            BlockEntityData::CyanWallBanner(_) => BlockEntityVariant::CyanWallBanner,
            BlockEntityData::PurpleBanner(_) => BlockEntityVariant::PurpleBanner,
            BlockEntityData::PurpleWallBanner(_) => BlockEntityVariant::PurpleWallBanner,
            BlockEntityData::BlueBanner(_) => BlockEntityVariant::BlueBanner,
            BlockEntityData::BlueWallBanner(_) => BlockEntityVariant::BlueWallBanner,
            BlockEntityData::BrownBanner(_) => BlockEntityVariant::BrownBanner,
            BlockEntityData::BrownWallBanner(_) => BlockEntityVariant::BrownWallBanner,
            BlockEntityData::GreenBanner(_) => BlockEntityVariant::GreenBanner,
            BlockEntityData::GreenWallBanner(_) => BlockEntityVariant::GreenWallBanner,
            BlockEntityData::RedBanner(_) => BlockEntityVariant::RedBanner,
            BlockEntityData::RedWallBanner(_) => BlockEntityVariant::RedWallBanner,
            BlockEntityData::BlackBanner(_) => BlockEntityVariant::BlackBanner,
            BlockEntityData::BlackWallBanner(_) => BlockEntityVariant::BlackWallBanner,
        }
    }

    // This could probably be like a derive macro, field attribute like thing.
    pub fn to_id(&self) -> &'static str {
        match self {
            BlockEntityData::Barrel(_) => "minecraft:barrel",
            BlockEntityData::Beacon(_) => "minecraft:beacon",
            BlockEntityData::Beehive(_) => "minecraft:beehive",
            BlockEntityData::Bell => "minecraft:bell",
            BlockEntityData::BlastFurnace(_) => "minecraft:blast_furnace",
            BlockEntityData::BrewingStand(_) => "minecraft:brewing_stand",
            BlockEntityData::CalibratedSculkSensor(_) => "minecraft:calibrated_sculk_sensor",
            BlockEntityData::Campfire(_) => "minecraft:campfire",
            BlockEntityData::ChiseledBookshelf(_) => "minecraft:chiseled_bookshelf",
            BlockEntityData::Chest(_) => "minecraft:chest",
            BlockEntityData::Comparator(_) => "minecraft:comparator",
            BlockEntityData::CommandBlock(_) => "minecraft:command_block",
            BlockEntityData::Conduit(_) => "minecraft:conduit",
            BlockEntityData::Crafter(_) => "minecraft:crafter",
            BlockEntityData::DaylightDetector => "minecraft:daylight_detector",
            BlockEntityData::DecoratedPot(_) => "minecraft:decorated_pot",
            BlockEntityData::Dispenser(_) => "minecraft:dispenser",
            BlockEntityData::Dropper(_) => "minecraft:dropper",
            BlockEntityData::EnchantingTable(_) => "minecraft:enchanting_table",
            BlockEntityData::EnderChest => "minecraft:ender_chest",
            BlockEntityData::EndGateway(_) => "minecraft:end_gateway",
            BlockEntityData::EndPortal => "minecraft:end_portal",
            BlockEntityData::Furnace(_) => "minecraft:furnace",
            BlockEntityData::Hopper(_) => "minecraft:hopper",
            BlockEntityData::Jigsaw(_) => "minecraft:jigsaw",
            BlockEntityData::Jukebox(_) => "minecraft:jukebox",
            BlockEntityData::Lectern(_) => "minecraft:lectern",
            BlockEntityData::MobSpawner(_) => "minecraft:mob_spawner",
            BlockEntityData::Piston(_) => "minecraft:piston",
            BlockEntityData::SculkCatalyst(_) => "minecraft:sculk_catalyst",
            BlockEntityData::SculkSensor(_) => "minecraft:sculk_sensor",
            BlockEntityData::SculkShrieker(_) => "minecraft:sculk_shrieker",
            BlockEntityData::StructureBlock(_) => "minecraft:structure_block",
            BlockEntityData::Smoker(_) => "minecraft:smoker",
            BlockEntityData::SoulCampfire(_) => "minecraft:soul_campfire",
            BlockEntityData::SuspiciousGravel(_) => "minecraft:suspicious_gravel",
            BlockEntityData::SuspiciousSand(_) => "minecraft:suspicious_sand",
            BlockEntityData::TrappedChest(_) => "minecraft:trapped_chest",
            BlockEntityData::TrialSpawner(_) => "minecraft:trial_spawner",
            BlockEntityData::Vault(_) => "minecraft:vault",
            //
            BlockEntityData::SkeletonSkull(_) => "minecraft:skeleton_skull",
            BlockEntityData::SkeletonWallSkull(_) => "minecraft:skeleton_wall_skull",
            BlockEntityData::WitherSkeletonSkull(_) => "minecraft:wither_skeleton_skull",
            BlockEntityData::WitherSkeletonWallSkull(_) => "minecraft:wither_skeleton_wall_skull",
            BlockEntityData::ZombieHead(_) => "minecraft:zombie_head",
            BlockEntityData::ZombieWallHead(_) => "minecraft:zombie_wall_head",
            BlockEntityData::PlayerHead(_) => "minecraft:player_head",
            BlockEntityData::PlayerWallHead(_) => "minecraft:player_wall_head",
            BlockEntityData::CreeperHead(_) => "minecraft:creeper_head",
            BlockEntityData::CreeperWallHead(_) => "minecraft:creeper_wall_head",
            BlockEntityData::DragonHead(_) => "minecraft:dragon_head",
            BlockEntityData::DragonWallHead(_) => "minecraft:dragon_wall_head",
            BlockEntityData::PiglinHead(_) => "minecraft:piglin_head",
            BlockEntityData::PiglinWallHead(_) => "minecraft:piglin_wall_head",
            //
            BlockEntityData::OakHangingSign(_) => "minecraft:oak_hanging_sign",
            BlockEntityData::OakWallHangingSign(_) => "minecraft:oak_wall_hanging_sign",
            BlockEntityData::SpruceHangingSign(_) => "minecraft:spruce_hanging_sign",
            BlockEntityData::SpruceWallHangingSign(_) => "minecraft:spruce_wall_hanging_sign",
            BlockEntityData::BirchHangingSign(_) => "minecraft:birch_hanging_sign",
            BlockEntityData::BirchWallHangingSign(_) => "minecraft:birch_wall_hanging_sign",
            BlockEntityData::JungleHangingSign(_) => "minecraft:jungle_hanging_sign",
            BlockEntityData::JungleWallHangingSign(_) => "minecraft:jungle_wall_hanging_sign",
            BlockEntityData::AcaciaHangingSign(_) => "minecraft:acacia_hanging_sign",
            BlockEntityData::AcaciaWallHangingSign(_) => "minecraft:acacia_wall_hanging_sign",
            BlockEntityData::DarkOakHangingSign(_) => "minecraft:dark_oak_hanging_sign",
            BlockEntityData::DarkOakWallHangingSign(_) => "minecraft:dark_oak_wall_hanging_sign",
            BlockEntityData::MangroveHangingSign(_) => "minecraft:mangrove_hanging_sign",
            BlockEntityData::MangroveWallHangingSign(_) => "minecraft:mangrove_wall_hanging_sign",
            BlockEntityData::CherryHangingSign(_) => "minecraft:cherry_hanging_sign",
            BlockEntityData::CherryWallHangingSign(_) => "minecraft:cherry_wall_hanging_sign",
            BlockEntityData::BambooHangingSign(_) => "minecraft:bamboo_hanging_sign",
            BlockEntityData::BambooWallHangingSign(_) => "minecraft:bamboo_wall_hanging_sign",
            BlockEntityData::CrimsonHangingSign(_) => "minecraft:crimson_hanging_sign",
            BlockEntityData::CrimsonWallHangingSign(_) => "minecraft:crimson_wall_hanging_sign",
            BlockEntityData::WarpedHangingSign(_) => "minecraft:warped_hanging_sign",
            BlockEntityData::WarpedWallHangingSign(_) => "minecraft:warped_wall_hanging_sign",
            //
            BlockEntityData::OakSign(_) => "minecraft:oak_sign",
            BlockEntityData::OakWallSign(_) => "minecraft:oak_wall_sign",
            BlockEntityData::SpruceSign(_) => "minecraft:spruce_sign",
            BlockEntityData::SpruceWallSign(_) => "minecraft:spruce_wall_sign",
            BlockEntityData::BirchSign(_) => "minecraft:birch_sign",
            BlockEntityData::BirchWallSign(_) => "minecraft:birch_wall_sign",
            BlockEntityData::JungleSign(_) => "minecraft:jungle_sign",
            BlockEntityData::JungleWallSign(_) => "minecraft:jungle_wall_sign",
            BlockEntityData::AcaciaSign(_) => "minecraft:acacia_sign",
            BlockEntityData::AcaciaWallSign(_) => "minecraft:acacia_wall_sign",
            BlockEntityData::DarkOakSign(_) => "minecraft:dark_oak_sign",
            BlockEntityData::DarkOakWallSign(_) => "minecraft:dark_oak_wall_sign",
            BlockEntityData::MangroveSign(_) => "minecraft:mangrove_sign",
            BlockEntityData::MangroveWallSign(_) => "minecraft:mangrove_wall_sign",
            BlockEntityData::CherrySign(_) => "minecraft:cherry_sign",
            BlockEntityData::CherryWallSign(_) => "minecraft:cherry_wall_sign",
            BlockEntityData::BambooSign(_) => "minecraft:bamboo_sign",
            BlockEntityData::BambooWallSign(_) => "minecraft:bamboo_wall_sign",
            BlockEntityData::CrimsonSign(_) => "minecraft:crimson_sign",
            BlockEntityData::CrimsonWallSign(_) => "minecraft:crimson_wall_sign",
            BlockEntityData::WarpedSign(_) => "minecraft:warped_sign",
            BlockEntityData::WarpedWallSign(_) => "minecraft:warped_wall_sign",
            //
            BlockEntityData::WhiteShulkerBox(_) => "minecraft:white_shulker_box",
            BlockEntityData::OrangeShulkerBox(_) => "minecraft:orange_shulker_box",
            BlockEntityData::MagentaShulkerBox(_) => "minecraft:magenta_shulker_box",
            BlockEntityData::LightBlueShulkerBox(_) => "minecraft:light_blue_shulker_box",
            BlockEntityData::YellowShulkerBox(_) => "minecraft:yellow_shulker_box",
            BlockEntityData::LimeShulkerBox(_) => "minecraft:lime_shulker_box",
            BlockEntityData::PinkShulkerBox(_) => "minecraft:pink_shulker_box",
            BlockEntityData::GrayShulkerBox(_) => "minecraft:gray_shulker_box",
            BlockEntityData::LightGrayShulkerBox(_) => "minecraft:light_gray_shulker_box",
            BlockEntityData::CyanShulkerBox(_) => "minecraft:cyan_shulker_box",
            BlockEntityData::PurpleShulkerBox(_) => "minecraft:purple_shulker_box",
            BlockEntityData::BlueShulkerBox(_) => "minecraft:blue_shulker_box",
            BlockEntityData::BrownShulkerBox(_) => "minecraft:brown_shulker_box",
            BlockEntityData::GreenShulkerBox(_) => "minecraft:green_shulker_box",
            BlockEntityData::RedShulkerBox(_) => "minecraft:red_shulker_box",
            BlockEntityData::BlackShulkerBox(_) => "minecraft:black_shulker_box",
            //
            BlockEntityData::WhiteBed => "minecraft:white_bed",
            BlockEntityData::OrangeBed => "minecraft:orange_bed",
            BlockEntityData::MagentaBed => "minecraft:magenta_bed",
            BlockEntityData::LightBlueBed => "minecraft:light_blue_bed",
            BlockEntityData::YellowBed => "minecraft:yellow_bed",
            BlockEntityData::LimeBed => "minecraft:lime_bed",
            BlockEntityData::PinkBed => "minecraft:pink_bed",
            BlockEntityData::GrayBed => "minecraft:gray_bed",
            BlockEntityData::LightGrayBed => "minecraft:light_gray_bed",
            BlockEntityData::CyanBed => "minecraft:cyan_bed",
            BlockEntityData::PurpleBed => "minecraft:purple_bed",
            BlockEntityData::BlueBed => "minecraft:blue_bed",
            BlockEntityData::BrownBed => "minecraft:brown_bed",
            BlockEntityData::GreenBed => "minecraft:green_bed",
            BlockEntityData::RedBed => "minecraft:red_bed",
            BlockEntityData::BlackBed => "minecraft:black_bed",
            //
            BlockEntityData::WhiteBanner(_) => "minecraft:white_banner",
            BlockEntityData::WhiteWallBanner(_) => "minecraft:white_wall_banner",
            BlockEntityData::OrangeBanner(_) => "minecraft:orange_banner",
            BlockEntityData::OrangeWallBanner(_) => "minecraft:orange_wall_banner",
            BlockEntityData::MagentaBanner(_) => "minecraft:magenta_banner",
            BlockEntityData::MagentaWallBanner(_) => "minecraft:magenta_wall_banner",
            BlockEntityData::LightBlueBanner(_) => "minecraft:light_blue_banner",
            BlockEntityData::LightBlueWallBanner(_) => "minecraft:light_blue_wall_banner",
            BlockEntityData::YellowBanner(_) => "minecraft:yellow_banner",
            BlockEntityData::YellowWallBanner(_) => "minecraft:yellow_wall_banner",
            BlockEntityData::LimeBanner(_) => "minecraft:lime_banner",
            BlockEntityData::LimeWallBanner(_) => "minecraft:lime_wall_banner",
            BlockEntityData::PinkBanner(_) => "minecraft:pink_banner",
            BlockEntityData::PinkWallBanner(_) => "minecraft:pink_wall_banner",
            BlockEntityData::GrayBanner(_) => "minecraft:gray_banner",
            BlockEntityData::GrayWallBanner(_) => "minecraft:gray_wall_banner",
            BlockEntityData::LightGrayBanner(_) => "minecraft:light_gray_banner",
            BlockEntityData::LightGrayWallBanner(_) => "minecraft:light_gray_wall_banner",
            BlockEntityData::CyanBanner(_) => "minecraft:cyan_banner",
            BlockEntityData::CyanWallBanner(_) => "minecraft:cyan_wall_banner",
            BlockEntityData::PurpleBanner(_) => "minecraft:purple_banner",
            BlockEntityData::PurpleWallBanner(_) => "minecraft:purple_wall_banner",
            BlockEntityData::BlueBanner(_) => "minecraft:blue_banner",
            BlockEntityData::BlueWallBanner(_) => "minecraft:blue_wall_banner",
            BlockEntityData::BrownBanner(_) => "minecraft:brown_banner",
            BlockEntityData::BrownWallBanner(_) => "minecraft:brown_wall_banner",
            BlockEntityData::GreenBanner(_) => "minecraft:green_banner",
            BlockEntityData::GreenWallBanner(_) => "minecraft:green_wall_banner",
            BlockEntityData::RedBanner(_) => "minecraft:red_banner",
            BlockEntityData::RedWallBanner(_) => "minecraft:red_wall_banner",
            BlockEntityData::BlackBanner(_) => "minecraft:black_banner",
            BlockEntityData::BlackWallBanner(_) => "minecraft:black_wall_banner",
        }
    }
}
